version: '3'

services:
  web:
    image: nginx:1.21.3
    ports:
      - '3001:80'
    volumes:
      - ./src:/var/www/docker-demo
      - ./virtual-host.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysqldb
      - php
    links:
      - mysqldb
      - php

  php:
    image: php:8.0-fpm
    volumes:
      - ./src:/var/www/docker-demo

  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
