version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 5001:80
    volumes:
      - ./src:/var/www/html
      - ./virtual-host.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
