version: '3'

services:
  nginx:
    image: nginx:1.13.8
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./virtual-host.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
